import { getDb } from './index.js';
import { greenCoffeeLots } from './schema.js';

// 6 realistic Colombian green coffee lots covering all five pricing
// strategies. Lot #6 is INVITE_ONLY and visible=false, per the spec's
// "initially hidden with option to display if no takers" behavior.
//
// Deliberately empty: rfqs, sampleRequests, sourcingRequests,
// verificationRequests — those tables only ever hold real submissions.
const lots = [
  {
    lotCode: 'FNC-24-118',
    title: 'Finca El Mirador',
    inventoryType: 'FINCAVA_OWNED' as const,
    status: 'AVAILABLE' as const,
    visible: true,
    variety: 'Caturra',
    process: 'Washed',
    region: 'Huila',
    farm: 'Finca El Mirador',
    producer: 'Familia Rojas',
    altitude: '1,750m',
    harvestDate: new Date('2024-07-15'),
    harvestWindow: 'Jun – Aug',
    availableKg: '2400',
    cupScore: '86.5',
    moisture: '10.8',
    waterActivity: '0.55',
    screenSize: '15/16',
    tastingNotes: 'Bright, floral cup with notes of red apple, panela and jasmine.',
    certifications: ['Rainforest Alliance'],
    exportReadiness: 'FOB Buenaventura, ready to ship',
    sampleAvailable: true,
    images: [],
    pricingStrategy: 'PUBLIC' as const,
    currency: 'USD',
    pricePerKg: '6.85',
    incoterm: 'FOB Buenaventura',
    priceNotesPublic: 'Exact FOB pricing, confirmed with current harvest.',
  },
  {
    lotCode: 'FNC-24-092',
    title: 'Finca Buenavista',
    inventoryType: 'FINCAVA_CONTROLLED' as const,
    status: 'LIMITED_QUANTITY' as const,
    visible: true,
    variety: 'Bourbon',
    process: 'Honey',
    region: 'Nariño',
    farm: 'Finca Buenavista',
    producer: 'Cooperativa Alto Nariño',
    altitude: '1,900m',
    harvestDate: new Date('2024-06-01'),
    harvestWindow: 'May – Jul',
    availableKg: '900',
    cupScore: '87.25',
    moisture: '11.0',
    waterActivity: '0.53',
    screenSize: '16/17',
    tastingNotes: 'Syrupy body, notes of caramel, dried apricot and orange zest.',
    certifications: [],
    exportReadiness: 'FOB Buenaventura, ready to ship',
    sampleAvailable: true,
    images: [],
    pricingStrategy: 'STARTING_FROM' as const,
    currency: 'USD',
    pricePerKg: '7.40',
    incoterm: 'FOB Buenaventura',
    priceNotesPublic: 'Starting price; final price depends on volume committed.',
  },
  {
    lotCode: 'FNC-24-201',
    title: 'Finca La Esperanza',
    inventoryType: 'EXCLUSIVE_PARTNER' as const,
    status: 'SAMPLE_AVAILABLE' as const,
    visible: true,
    variety: 'Geisha',
    process: 'Natural',
    region: 'Cauca',
    farm: 'Finca La Esperanza',
    producer: 'Familia Muñoz',
    altitude: '2,000m',
    harvestDate: new Date('2024-09-01'),
    harvestWindow: 'Aug – Oct',
    availableKg: '350',
    cupScore: '89.0',
    moisture: '10.5',
    waterActivity: '0.52',
    screenSize: '15/16',
    tastingNotes: 'Jasmine, bergamot and stone fruit, delicate and tea-like.',
    certifications: [],
    exportReadiness: 'Samples ready; commercial volume post-harvest',
    sampleAvailable: true,
    images: [],
    pricingStrategy: 'MARKET_RANGE' as const,
    currency: 'USD',
    priceRangeLowPerKg: '9.20',
    priceRangeHighPerKg: '9.80',
    incoterm: 'FOB Buenaventura',
    priceNotesPublic: 'Range reflects current comparable Geisha lot pricing.',
  },
  {
    lotCode: 'FNC-25-004',
    title: 'Finca Palmares',
    inventoryType: 'FUTURE_HARVEST' as const,
    status: 'COMING_SOON' as const,
    visible: true,
    variety: 'Typica',
    process: 'Washed',
    region: 'Tolima',
    farm: 'Finca Palmares',
    producer: 'Cooperativa Palmares',
    altitude: '1,650m',
    harvestDate: new Date('2025-06-01'),
    harvestWindow: 'May – Jul 2025',
    availableKg: '3000',
    cupScore: '85.0',
    moisture: null,
    waterActivity: null,
    screenSize: null,
    tastingNotes: 'Classic Tolima cup: milk chocolate, brown sugar, light citrus.',
    certifications: [],
    exportReadiness: 'Not yet harvested',
    sampleAvailable: false,
    images: [],
    pricingStrategy: 'RFQ_ONLY' as const,
    currency: 'USD',
    priceNotesPublic: 'Pre-harvest allocation — contact us to reserve volume.',
  },
  {
    lotCode: 'FNC-24-155',
    title: 'Finca San Rafael',
    inventoryType: 'BROKERED' as const,
    status: 'AVAILABLE' as const,
    visible: true,
    variety: 'Castillo',
    process: 'Washed',
    region: 'Huila',
    farm: 'Finca San Rafael',
    producer: 'Familia Torres',
    altitude: '1,800m',
    harvestDate: new Date('2024-07-01'),
    harvestWindow: 'Jun – Aug',
    availableKg: '1800',
    cupScore: '84.5',
    moisture: '11.2',
    waterActivity: '0.56',
    screenSize: '14/15',
    tastingNotes: 'Balanced, sweet, notes of milk chocolate and red grape.',
    certifications: [],
    exportReadiness: 'FOB Buenaventura, ready to ship',
    sampleAvailable: true,
    images: [],
    pricingStrategy: 'RFQ_ONLY' as const,
    currency: 'USD',
    priceNotesPublic: 'Submit an RFQ for current FOB pricing.',
  },
  {
    lotCode: 'FNC-23-310',
    title: 'Finca Alto Verde',
    inventoryType: 'EXCLUSIVE_PARTNER' as const,
    status: 'RESERVED' as const,
    // INVITE_ONLY defaults to hidden — admin can flip visible=true if there
    // are no takers among the invited buyers.
    visible: false,
    variety: 'Caturra',
    process: 'Natural',
    region: 'Nariño',
    farm: 'Finca Alto Verde',
    producer: 'Familia Ortega',
    altitude: '1,950m',
    harvestDate: new Date('2023-08-01'),
    harvestWindow: 'Jul – Sep',
    availableKg: '600',
    cupScore: '86.0',
    moisture: '10.9',
    waterActivity: '0.54',
    screenSize: '15/16',
    tastingNotes: 'Winey natural, notes of blackberry, cocoa and molasses.',
    certifications: [],
    exportReadiness: 'FOB Buenaventura, ready to ship',
    sampleAvailable: false,
    images: [],
    pricingStrategy: 'INVITE_ONLY' as const,
    currency: 'USD',
    priceNotesPublic: 'Invite-only allocation — contact FINCAVA for access.',
  },
];

async function seed(): Promise<void> {
  const db = getDb();

  console.log(`Seeding ${lots.length} green coffee lots...`);
  await db.insert(greenCoffeeLots).values(lots).onConflictDoNothing({
    target: greenCoffeeLots.lotCode,
  });
  console.log('Seed complete.');
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  });
