import { Router } from 'express';
import { Resend } from 'resend';
import { env } from '../env.js';
import { logger } from '../logger.js';
import { renderEmailLayout } from '../email/templates/layout.js';

export const adminRouter = Router();

// Auth is enforced by requireAdminSession at the app.ts mount point, not
// here — same session-cookie gate as every other /api/admin/* route.

// POST /api/admin/smoke-email
// Sends a test email to FOUNDER_EMAIL via Resend and returns the message ID.
// Designed to be called once after every deployment to confirm email is working.
// Does NOT go through sendEmail() so the result is synchronous (caller sees
// the Resend response directly) and the log entry shows up as a regular send.
adminRouter.post('/smoke-email', async (req, res, next) => {
  try {
    if (!env.RESEND_API_KEY || !env.EMAIL_FROM) {
      res.status(503).json({
        ok: false,
        error: 'Resend is not configured — add RESEND_API_KEY and EMAIL_FROM to Replit Secrets',
      });
      return;
    }

    if (!env.FOUNDER_EMAIL) {
      res.status(503).json({
        ok: false,
        error: 'FOUNDER_EMAIL is not set — add it to Replit Secrets',
      });
      return;
    }

    const sentAt = new Date().toISOString();
    const from = env.EMAIL_FROM;
    const to = env.FOUNDER_EMAIL;

    const html = renderEmailLayout(`
      <p><strong>FINCAVA email smoke test</strong></p>
      <p>This message confirms that the Resend integration is configured correctly and
      email delivery is working end-to-end.</p>
      <table role="presentation" cellpadding="0" cellspacing="0" style="font-size:14px;margin-top:8px;">
        <tr>
          <td style="padding:4px 12px 4px 0;color:#6b6459;">From</td>
          <td>${from}</td>
        </tr>
        <tr>
          <td style="padding:4px 12px 4px 0;color:#6b6459;">To</td>
          <td>${to}</td>
        </tr>
        <tr>
          <td style="padding:4px 12px 4px 0;color:#6b6459;">Sent at</td>
          <td>${sentAt}</td>
        </tr>
      </table>
      <p style="margin-top:16px;color:#6b6459;font-size:13px;">You can safely ignore this message — it was generated by the deployment smoke test.</p>
    `);

    const text = [
      'FINCAVA email smoke test',
      '',
      'This message confirms that the Resend integration is configured correctly and email delivery is working end-to-end.',
      '',
      `From:    ${from}`,
      `To:      ${to}`,
      `Sent at: ${sentAt}`,
      '',
      'You can safely ignore this message — it was generated by the deployment smoke test.',
    ].join('\n');

    const resend = new Resend(env.RESEND_API_KEY);
    const { data, error } = await resend.emails.send({
      from,
      to,
      subject: 'FINCAVA email smoke test',
      html,
      text,
    });

    if (error) {
      logger.error({ error }, 'Admin smoke-email: Resend returned an error');
      res.status(502).json({ ok: false, error });
      return;
    }

    logger.info({ messageId: data?.id, to }, 'Admin smoke-email: accepted by Resend');
    res.json({ ok: true, messageId: data?.id, to, sentAt });
  } catch (err) {
    next(err);
  }
});
