/**
 * Email delivery smoke test
 *
 * Sends a single test email via the Resend API using the configured
 * credentials (RESEND_API_KEY, EMAIL_FROM, FOUNDER_EMAIL) and exits with
 * a clear success or failure message.
 *
 * Run from the repo root:
 *   npm run smoke:email --workspace server
 *
 * Or from the server/ directory:
 *   npm run smoke:email
 */

import path from 'node:path';
import dotenv from 'dotenv';

dotenv.config({ path: path.resolve(import.meta.dirname, '../../.env') });

import { Resend } from 'resend';
import { renderEmailLayout } from '../src/email/templates/layout.js';

const RESEND_API_KEY = process.env['RESEND_API_KEY'];
const EMAIL_FROM = process.env['EMAIL_FROM'];
const FOUNDER_EMAIL = process.env['FOUNDER_EMAIL'];

function check(name: string, value: string | undefined): string {
  if (!value) {
    console.error(`✗  ${name} is not set — add it to Replit Secrets`);
    process.exit(1);
  }
  return value;
}

const apiKey = check('RESEND_API_KEY', RESEND_API_KEY);
const from = check('EMAIL_FROM', EMAIL_FROM);
const to = check('FOUNDER_EMAIL', FOUNDER_EMAIL);

const resend = new Resend(apiKey);

const sentAt = new Date().toISOString();

const html = renderEmailLayout(`
  <p><strong>FINCAVA email smoke test</strong></p>
  <p>This message confirms that the Resend integration is configured correctly and
  email delivery is working end-to-end.</p>
  <table role="presentation" cellpadding="0" cellspacing="0" style="font-size:14px;margin-top:8px;">
    <tr>
      <td style="padding:4px 12px 4px 0;color:#6b6459;">From</td>
      <td>${from}</td>
    </tr>
    <tr>
      <td style="padding:4px 12px 4px 0;color:#6b6459;">To</td>
      <td>${to}</td>
    </tr>
    <tr>
      <td style="padding:4px 12px 4px 0;color:#6b6459;">Sent at</td>
      <td>${sentAt}</td>
    </tr>
  </table>
  <p style="margin-top:16px;color:#6b6459;font-size:13px;">You can safely ignore this message — it was generated by the deployment smoke test.</p>
`);

const text = [
  'FINCAVA email smoke test',
  '',
  'This message confirms that the Resend integration is configured correctly and email delivery is working end-to-end.',
  '',
  `From:    ${from}`,
  `To:      ${to}`,
  `Sent at: ${sentAt}`,
  '',
  'You can safely ignore this message — it was generated by the deployment smoke test.',
].join('\n');

console.log(`Sending smoke-test email…`);
console.log(`  From: ${from}`);
console.log(`  To:   ${to}`);

const { data, error } = await resend.emails.send({
  from,
  to,
  subject: 'FINCAVA email smoke test',
  html,
  text,
});

if (error) {
  console.error('\n✗  Resend returned an error:');
  console.error(JSON.stringify(error, null, 2));
  console.error('\nCommon causes:');
  console.error('  • The sender domain in EMAIL_FROM has not been verified in the Resend dashboard');
  console.error('  • SPF / DKIM records are missing or not yet propagated');
  console.error('  • RESEND_API_KEY is invalid or revoked');
  process.exit(1);
}

console.log('\n✓  Email accepted by Resend');
console.log(`   Message ID: ${data?.id}`);
console.log(`\nNext step: check the inbox at ${to} to confirm delivery.`);
console.log('If the message is missing, check the Resend dashboard → Logs for delivery status.');
